// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import clientLoaders from './loaders.js';
import React from 'react';

export async function getRoutes() {
  const routes = {"1":{"path":"/","parentId":"@@/global-layout","id":"1"},"2":{"path":"/account","parentId":"1","id":"2"},"3":{"path":"/account/login","parentId":"2","id":"3"},"4":{"path":"/account/loginwith2fa","parentId":"2","id":"4"},"5":{"path":"/account/loginwithrecoverycode","parentId":"2","id":"5"},"6":{"path":"/settings","parentId":"1","id":"6"},"7":{"path":"/settings/profile","parentId":"6","id":"7"},"8":{"path":"/settings/account","parentId":"6","id":"8"},"9":{"path":"/settings/security","parentId":"6","id":"9"},"10":{"path":"/settings/2fa","parentId":"6","id":"10"},"11":{"path":"/settings/2fa/enable-authenticator","parentId":"10","id":"11"},"12":{"path":"/settings/2fa/show-recovery-codes","parentId":"10","id":"12"},"13":{"path":"/settings/2fa/recovery-codes","parentId":"10","id":"13"},"14":{"path":"/","parentId":"1","id":"14"},"15":{"path":"/*","parentId":"@@/global-layout","id":"15"},"@@/global-layout":{"id":"@@/global-layout","path":"/","isLayout":true}} as const;
  return {
    routes,
    routeComponents: {
'1': React.lazy(() => import(/* webpackChunkName: "layouts__index" */'@/layouts/index.tsx')),
'2': React.lazy(() => import(/* webpackChunkName: "layouts__account" */'@/layouts/account.tsx')),
'3': React.lazy(() => import(/* webpackChunkName: "p__account__login" */'@/pages/account/login.tsx')),
'4': React.lazy(() => import(/* webpackChunkName: "p__account__loginwith2fa" */'@/pages/account/loginwith2fa.tsx')),
'5': React.lazy(() => import(/* webpackChunkName: "p__account__loginwithrecoverycode" */'@/pages/account/loginwithrecoverycode.tsx')),
'6': React.lazy(() => import(/* webpackChunkName: "layouts__settings" */'@/layouts/settings.tsx')),
'7': React.lazy(() => import(/* webpackChunkName: "p__settings__profile" */'@/pages/settings/profile.tsx')),
'8': React.lazy(() => import(/* webpackChunkName: "p__settings__account" */'@/pages/settings/account.tsx')),
'9': React.lazy(() => import(/* webpackChunkName: "p__settings__security" */'@/pages/settings/security.tsx')),
'10': React.lazy(() => import( './EmptyRoute')),
'11': React.lazy(() => import(/* webpackChunkName: "p__settings__2fa__enableauthenticator" */'@/pages/settings/2fa/enableauthenticator.tsx')),
'12': React.lazy(() => import(/* webpackChunkName: "p__settings__2fa__showrecoverycodes" */'@/pages/settings/2fa/showrecoverycodes.tsx')),
'13': React.lazy(() => import(/* webpackChunkName: "p__settings__2fa__recoverycodes" */'@/pages/settings/2fa/recoverycodes.tsx')),
'14': React.lazy(() => import(/* webpackChunkName: "p__index" */'@/pages/index.tsx')),
'15': React.lazy(() => import(/* webpackChunkName: "p__404" */'@/pages/404.tsx')),
'@@/global-layout': React.lazy(() => import(/* webpackChunkName: "layouts__index" */'/Users/andezeng/Codes/ka-group/LinkMore.KA.AM/src/LinkMore.KA.AM.Web/ClientApp/src/layouts/index.tsx')),
},
  };
}
