// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import model_1 from '/Users/andezeng/Codes/BeniceSoft/OpenAuthing/admin-ui/src/models/clients';
import model_2 from '/Users/andezeng/Codes/BeniceSoft/OpenAuthing/admin-ui/src/models/createIdP';
import model_3 from '/Users/andezeng/Codes/BeniceSoft/OpenAuthing/admin-ui/src/models/departments';
import model_4 from '/Users/andezeng/Codes/BeniceSoft/OpenAuthing/admin-ui/src/models/idps';
import model_5 from '/Users/andezeng/Codes/BeniceSoft/OpenAuthing/admin-ui/src/models/idpTemplates';
import model_6 from '/Users/andezeng/Codes/BeniceSoft/OpenAuthing/admin-ui/src/models/login';
import model_7 from '/Users/andezeng/Codes/BeniceSoft/OpenAuthing/admin-ui/src/models/roles';
import model_8 from '/Users/andezeng/Codes/BeniceSoft/OpenAuthing/admin-ui/src/models/twofactor';
import model_9 from '/Users/andezeng/Codes/BeniceSoft/OpenAuthing/admin-ui/src/models/users';

export const models = {
model_1: { namespace: 'clients', model: model_1 },
model_2: { namespace: 'createIdP', model: model_2 },
model_3: { namespace: 'departments', model: model_3 },
model_4: { namespace: 'idps', model: model_4 },
model_5: { namespace: 'idpTemplates', model: model_5 },
model_6: { namespace: 'login', model: model_6 },
model_7: { namespace: 'roles', model: model_7 },
model_8: { namespace: 'twofactor', model: model_8 },
model_9: { namespace: 'users', model: model_9 },
} as const
