// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import model_1 from '/Users/andezeng/Codes/BeniceSoft/OpenAuthing/admin-ui/src/pages/admin/clients/models/clientDetail';
import model_2 from '/Users/andezeng/Codes/BeniceSoft/OpenAuthing/admin-ui/src/pages/admin/permission/data/resources/models/management';
import model_3 from '/Users/andezeng/Codes/BeniceSoft/OpenAuthing/admin-ui/src/pages/admin/permission/roles/models/roleCreate';
import model_4 from '/Users/andezeng/Codes/BeniceSoft/OpenAuthing/admin-ui/src/pages/admin/permission/roles/models/roleDetail';
import model_5 from '/Users/andezeng/Codes/BeniceSoft/OpenAuthing/admin-ui/src/pages/admin/user-groups/detail/models/index';
import model_6 from '/Users/andezeng/Codes/BeniceSoft/OpenAuthing/admin-ui/src/pages/admin/user-groups/models/userGroupList';
import model_7 from '/Users/andezeng/Codes/BeniceSoft/OpenAuthing/admin-ui/src/pages/admin/users/detail/models/index';
import model_8 from '/Users/andezeng/Codes/BeniceSoft/OpenAuthing/admin-ui/src/.umi/plugin-initialState/@@initialState';
import model_9 from '/Users/andezeng/Codes/BeniceSoft/OpenAuthing/admin-ui/src/.umi/plugin-qiankun-slave/qiankunModel';

export const models = {
model_1: { namespace: 'admin.clients.clientDetail', model: model_1 },
model_2: { namespace: 'admin.permission.data.resources.management', model: model_2 },
model_3: { namespace: 'admin.permission.roles.roleCreate', model: model_3 },
model_4: { namespace: 'admin.permission.roles.roleDetail', model: model_4 },
model_5: { namespace: 'admin.user-groups.detail.index', model: model_5 },
model_6: { namespace: 'admin.user-groups.userGroupList', model: model_6 },
model_7: { namespace: 'admin.users.detail.index', model: model_7 },
model_8: { namespace: '@@initialState', model: model_8 },
model_9: { namespace: '@@qiankunStateFromMaster', model: model_9 },
} as const
