// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import model_1 from '/Users/andezeng/Codes/ka-group/LinkMore.KA.AM/src/LinkMore.KA.AM.Web/ClientApp/src/models/auth';
import model_2 from '/Users/andezeng/Codes/ka-group/LinkMore.KA.AM/src/LinkMore.KA.AM.Web/ClientApp/src/models/twofactor';

export const models = {
model_1: { namespace: 'auth', model: model_1 },
model_2: { namespace: 'twofactor', model: model_2 },
} as const
